name: paneuc
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - python=3.*
  - snakemake
  - bwa
  - samtools
  - bcftools
  - qualimap
  - whatshap
  - AdapterRemoval
  - pynvim
  - git-annex
